-- Run in Supabase SQL Editor.
-- Then create a PUBLIC Storage bucket named: maxwell-birthday

create table if not exists public.birthday_photos (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  public_url text not null,
  created_at timestamptz not null default now()
);

alter table public.birthday_photos enable row level security;

create policy "birthday photos public read"
on public.birthday_photos for select
to anon
using (true);

create policy "birthday photos public insert"
on public.birthday_photos for insert
to anon
with check (true);

create policy "birthday photos public delete"
on public.birthday_photos for delete
to anon
using (true);

-- Storage policies for the public bucket.
create policy "birthday storage public insert"
on storage.objects for insert
to anon
with check (bucket_id = 'maxwell-birthday');

create policy "birthday storage public read"
on storage.objects for select
to anon
using (bucket_id = 'maxwell-birthday');

create policy "birthday storage public delete"
on storage.objects for delete
to anon
using (bucket_id = 'maxwell-birthday');

-- Realtime: add birthday_photos to the supabase_realtime publication if not already present.
alter publication supabase_realtime add table public.birthday_photos;
